### PR TITLE
added neighborhood and transit info to routes

### PR DESCRIPTION
**Pull request by hadasah**
haven't changed the db.csv file yet, kept the new file separate for comparison temporarily

### CODE REVIEW

**Comment by nickswalker** [comment]
On the problem that "for some modes (buses), the fact of there being a stop is not that useful on its own":

Maybe we can treat this as metrics of a transit isochrone. Try to capture how much is reachable for a particular time budget from a given start point (e.g. area of a shade in the isochrone) or perhaps reachability from some number of anchor locations across Seattle that we care about (e.g. whether the anchor point is within some threshold color on the isochrone, like is it possible to reach CSE or Queen Anne from this location in less than 1 hour via transit?). This requires route+schedule knowledge, but there are APIs that sell that.

Isochrones
https://seattletransitblog.com/2016/03/15/seattle-transit-isochrone-map-generator/

API
https://developers.google.com/maps/documentation/distance-matrix/overview

**Comment by hadasah** [comment]
@nickswalker added a reachability score 1-3 based on max google maps public transit time between the location and a fixed set of locations (temporarily, CSE, green lake, beacon hill)

**Comment by hadasah** [comment]
TODO: 
- write bash script downloading stop info & triggering updates if needed
- move some neighborhood info (for the start/end locs) from the routes/db.csv to the locs/db.csv file.

Also, considering merging the locs and routes folders, since a lot of logic will probably end up shared. Thoughts @nickswalker ?

**Comment by nickswalker** [comment]
Yes, would merge those folders

**Comment by ztatlock** [comment]
@hadasah  Nice!!

FWIW, I'd like to keep all the location info in the locs table and use the `start` and `end` fields of the routes table as "foreign keys" into locs. I think that may be simpler?

Not sure about best way to handle "neighborhoods traversed". Do we need that for scheduler? Can we recompute on demand?

After this merges, I plan to reorganize the routes db into a directory of geojson and compute the table from those files.

**Comment by hadasah** [comment]
@nickswalker @ztatlock ready to merge
heads up, I did a little restructuring -- locs and routes are a single folder now. Some of my stuff can be cleaned up slightly, but I can come back to that later when we make more decisions about what to do

**Pull request merged**
